name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  lint-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Flake8
        run: pip install flake8

      - name: Lint Python Code
        run: flake8 airflow/dags/services/

  build-and-push:
    runs-on: ubuntu-latest
    needs: lint-python
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker Image Version
        id: vars
        run: |
          echo "tag=main-${{ github.run_number }}" >> $GITHUB_ENV
          echo "sha=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker Image with Version Tag
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/data-processor:${{ env.tag }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/data-processor:${{ env.tag }} ${{ secrets.DOCKER_USERNAME }}/data-processor:latest

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/data-processor:${{ env.tag }}
          docker push ${{ secrets.DOCKER_USERNAME }}/data-processor:latest
